### ISSUE TITLE
How to Connect to TestConnect24!

### ISSUE THREAD

**Issue by Pokeadecker** [TestConnect24/site#3]
If you want to connect to TestConnect24 service, you need

- Windows Computer

- Nintendo Wii

- Internet Connection

**Steps:**

1. First download a program called [fiddler](https://www.telerik.com/download/fiddler/fiddler4) your computer. 

Click [here](https://www.telerik.com/download/fiddler/fiddler4) to download.

2. Run "FiddlerSetup" and once installed, open Fiddler 4

3. Open "AutoResponder" and click "Add Rule".

4. Click the "StringToMatch" and type this in "Rule Editor"

Request URL Pattern: from http://miicontest.wapp.wii.com/first/XX.ces

Local file to return or *Action to execute: To http://testconnect24.ml/first/XX.ces

5. Repleace the "XX.ces" with your region.

`79.ces is europe`

`49.ces is USA`

6. Now, click save and go into tools, options, then connections.

7. Checkmark every except "Use PAC Script"

> "Allow remote computers to connect" is optional but uses most of your CPU.

9. Restart fiddler by closing it and running it again.

10. Now, head over to your Wii.

**Wii Setup:**

1. Go into Wii options, then Wii settings.

2. Go to Wii System Settings 2 and click Internet.

**If you already have a connection setup, skip "For Wireless and For Wired Steps"**

3. Pick an available connection and connect to the internet.

**For Wireless**

1. Click "Wireless Connection" and click "Search for an Access Point".

2. Then pick your WiFi and enter your WiFi password.

3. Now do I connection test and see if your connection was successful.

4. If connection was successful, click "No" to not Perform a Wii system update.

**For Wired**

1. You going to need a "USB to LAN adapter".

2. Click Wired and do a connection test to see if your connection was successful.

3. If connection was successful, click "No" to not Perform a Wii system update.

**Wii Setup: Continued**

4. Now, go into your connection #, Change settings and turn right into you see "Proxy Server".

5. Click "Use" and head over to "Advanced Settings".

6. Click "Proxy Server" and type in your IP Address.

**If you don't know your IP Address**

1. Head over to your computer and go into command prompt or cmd.

2. Type in `ipconfig`.

> IPv4 Address should be your IP Address.

**Wii Setup: Continued Again**

7. Next for port, type "8888".

8. Then "Confirm" and click "Save".

9. Do I connection test and if the connection was successful, click "No" to not Perform a Wii system update.

10. Head back to computer and check mark "Enable rules".

11. Now to make sure its works, Click any wiiconnect24 channel and click "Start".

> Example: Check Mii Out Channel

12. Now, if successful. It's should give you the error code:

`Error Code: 258404`

Instead of,

`Error Code: 252102`

That it, your now officially connected to TC24.

Thanks for join our service!

**Comment by JonM313** [comment]
Not the right place for this.

**Comment by JonM313** [comment]
Closing this cuz this isn’t the right place for it.

**Comment by JonM313** [comment]
Also locking conversation.
